### ISSUE TITLE
expand_wildcard defaults

### ISSUE THREAD

**Issue by MerlinHeidemanns** [macartan/CausalQueries#173]
_Issue_
Default for join_by is a character. Thus, having no join_by character requires the explicit definition of the argument as NULL. This is counterintuitive.
_Suggestion_
Change default to Null

**Comment by lilymedina** [comment]
Most commonly expressions need to be joined by a logical operator. I think we chose  `"|"` because is less restrictive and because we believe is often the desired behavior.  Can't remember.

If expressions don't need to be joined (i.e. no wildcard included) `join_by` doesn't change output.

 So `expand_wildcard('(Y[X=1])')` and `expand_wildcard('(Y[X=1])', join_by = NULL)` throw the same exp --`"(Y[X=1])"`

My sense is that it's better to keep the default argument as `"|"`. Perhaps in the function is unnecessary to check whether argument is not NULL, bc most likely it'll never be.
